# ~/.tmuxinator/mycroft.yml

name: appknox
root: ~/projects/appknox/

# Optional tmux socket
# socket_name: foo

# Runs before everything. Use it to start daemons etc.
# pre: sudo /etc/rc.d/mysqld start

# Runs in each window and pane before window/pane specific commands. Useful for setting up interpreter versions.
pre_window: source ~/.zshrc


# Pass command line options to tmux. Useful for specifying a different tmux.conf.
# tmux_options: -f ~/.tmux.mac.conf

# Change the command to call tmux.  This can be used by derivatives/wrappers like byobu.
tmux_command: byobu

# Specifies (by name or index) which window will be selected on project startup. If not set, the first window is used.
# startup_window: logs


# attach: false

# Runs after everything. Use it to attach to tmux with custom options etc.
post: tmux -CC attach -t moriarty

windows:

  - irene:
      root: ~/projects/appknox/irene/
      layout: dbdc,149x42,0,0{74x42,0,0[74x21,0,0,25,74x20,0,22,33],74x42,75,0[74x21,75,0,31,74x20,75,22,32]}
      panes:
        - deactivate && . ~/.nodeenvs/irene/bin/activate && ember serve
        - l
        - l
        - l


  - mycroft:
      root: ~/projects/appknox/mycroft/
      layout: dbdc,149x42,0,0{74x42,0,0[74x21,0,0,25,74x20,0,22,33],74x42,75,0[74x21,75,0,31,74x20,75,22,32]}
      panes:
        - wo mycroft && ./scripts/start_server.sh
        - wo mycroft && ./scripts/start_celery.sh
        - wo mycroft && eval $(./scripts/env_converter.py) && dsp
        - wo mycroft


  - moriarty:
      root: ~/projects/appknox/moriarty/
      layout: dbdc,149x42,0,0{74x42,0,0[74x21,0,0,25,74x20,0,22,33],74x42,75,0[74x21,75,0,31,74x20,75,22,32]}
      panes:
        - wo moriarty && export DEBUG=True && ./scripts/start_server.sh
        - wo moriarty && export DEBUG=True && dj devices
        - wo moriarty && export DEBUG=True
        - smo
