- hosts: all
  remote_user: chillaranand
  become: yes
  become_method: sudo

  vars:
    root_email: anand21nanda@gmail.com
    home: /home/chillaranand/

    ssh_users:
      - chillaranand

    utils:
      - clementine
      - vlc
      - compizconfig-settings-manager
      - compiz-plugins-extra
      - unity-tweak-tool
      - indicator-sysmonitor

      - build-essential
      - dconf-tools
      - arpon
      - tree
      - htop
      - nmap
      - npm
      - synapse
      - unzip
      - xcape
      - pastebinit
      - nethogs
      - fluxgui
      - git

      - tesseract-ocr

      - python-dev
      - python3-dev
      - python-pip
      - virtualenvwrapper

    ppas:
      - ppa:synapse-core/ppa
      - ppa:nathan-renniewaldock/flux


  tasks:
    - name: Add ppas
      apt_repository: repo={{ item }} state=present
      with_items: "{{ ppas }}"

    - name: Install packages
      apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
      with_items: "{{ utils }}"

   # - name: Install docker
      # command: curl -sSL https://get.docker.com/ | sudo bash


    - git: repo=git://foosball.example.org/path/to/repo.git
           dest: /home/chillaranand/.qfc
