- name: check if '{{ item }}' exists
  stat: path='{{ projects }}/elpy'
  register: repo


- name: clone '{{ item }}'
  git:
    repo: 'git@github.com:ChillarAnand/{{ item }}.git'
    dest: '{{ projects }}/elpy'
    accept_hostkey: yes
    key_file: '{{ ssh_key }}'
  when:
    repo.stat.exists == False
