    # ppas:
    #   - ppa:synapse-core/ppa
    #   - ppa:nathan-renniewaldock/flux

        # - name: Add third party PPAs
    #   apt_repository: repo={{ item }} state=present
    #   with_items: "{{ ppas }}"
