      # - compizconfig-settings-manager
      # - compiz-plugins-extra
      # - unity-tweak-tool
      # - indicator-sysmonitor
      # - dconf-tools
      # - npm
      # - synapse
      # - fluxgui
